version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=kafka
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  research_database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data/
    restart: always
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  connect:
    image: debezium/connect:1.3
    ports:
     - 8083:8083
    links:
     - kafka
     - research_database
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
